var lakes = [
            ' While Lake Superior is indeed a lake, it behaves more like an inland sea',
            'All of the four other Great Lakes, plus three more the size of Lake Erie, would fit inside of Lake Superior.',
            'Isle Royale is a massive island surrounded by Lake Superior. Within this island are several smaller lakes. Yes, thats a lake on a lake.',
            'Despite its massive size, Lake Superior is an extremely young formation by Earths standards (only 10,000 years old).',
            'There is enough water in Lake Superior to submerge all of North and South America in 1 foot of water.',
            'Lake Superior contains 3 quadrillion gallons of water (3,000,000,000,000,000). All five of the Great Lakes combined contain 6 quadrillion gallons.',
            'Contained within Lake Superior is a whopping 10% of the worlds fresh surface water.',
            'Its estimated there are about 100 million lake trout in Lake Superior. Thats nearly one-fifth of the human population of North America!',
            'There are small outlets through which water leaves Lake Superior. It takes two centuries for all the water in the lake to replace itself.',
            'Lake Erie is the fourth-largest Great Lake in surface area, and the smallest in depth. Its the 11th largest lake on the planet.',
            'There is alleged to be a 30- to 40-foot-long "monster" in Lake Erie named Bessie. The earliest recorded sighting goes back as early as 1793.',
            'Water in Lake Erie replaces itself in only 2.6 years, which is notable considering the water in Lake Superior takes two centuries.',
            'The original publication of Dr. Seusss The Lorax contained the line, "I hear things are just as bad up in Lake Erie." Fourteen years later, the Ohio Sea Grant Program wrote to Seuss to make the case that conditions had improved. He removed the line.',
            'Not only is lake Erie the smallest Great Lake when it comes to volume, but its surrounded by the most industry. Seventeen metropolitan areas, each with populations of more than 50,000, border the Lake Erie basin.',
            'During the War of 1812, the U.S. beat the British in a naval battle called the Battle of Lake Erie, forcing them to abandon Detroit.',
            'If not for the the Straits of Mackinac, Lake Michigan and Lake Huron might be considered one lake. Hydrologically speaking, they have the same mean water level and are considered one lake.',
            'The Keystone State was one of the largest and most luxurious wooden steamships running during the Civil War. In 1861, it disappeared. In 2013, it was found 30 miles northeast of Harrisville under 175 feet of water.',
            'Goderich Mine is the largest salt mine in the world. Part of it runs underneath Lake Huron, more than 500 meters underground.',
            'Below Lake Huron, there are 9,000-year-old animal-herding structures used by prehistoric people from when the water levels were significantly lower.',
            'There are massive sinkholes in Lake Huron that have high amounts of sulfur and low amounts of oxygen, almost replicating the conditions of Earths ancient oceans 3 million years ago. Unique ecosystems are contained within them.',
            'Lake Huron is the second largest among the Great Lakes, and the fifth largest in the world.',
            'In size, Lake Michigan ranks third among the Great Lakes, and sixth among all freshwater lakes in the world.',
            'Lake Michigan is the only Great Lake that is entirely within the borders of the United States.',
            'The largest fresh water sand dunes in the world line the shores of Lake Michigan.',
            'Because water enters and exits Lake Michigan through the same path, it takes 77 years longer for the water to replace itself than in Huron, despite their similarity in size and depth. (Lake Michigan: 99 years, Lake Huron: 22 years)',
            'When the temperature of Lake Michigan is below freezing, this happens.28. Within Lake Michigan there is a "triangle" with a similar reputation to the Bermuda Triangle, where a large amount of "strange disappearances" have occurred. There have also been alleged UFO sightings.',
            'Singapore, Mich., is a ghost town on the shores of Lake Michigan that was buried under sand in 1871. Because of severe weather conditions and a lack of resources due to the need to rebuild after the great Chicago fire, the town was lost completely.',
            'In the mid-19th century, Lake Michigan had a pirate problem. Their booty: timber. In fact, the demise of Singapore is due in large part to the rapidly deforested area surrounding the town.',
            'Jim Dreyer swam across Lake Michigan in 1998 (65 miles), and then in 2003, he swam the length of Lake Michigan (422 miles).',
            'Lake Michigan was the location of the first recorded "Big Great Lakes disaster," in which a steamer carrying 600 people collided with a schooner delivering timber to Chicago. Four hundred and fifty people died.',
            'Lake Ontario is the smallest of the Great Lakes in surface area, and second smallest in depth. It\'s the 14th largest lake on the planet.',,
            'The province Ontario was named after the lake, and not vice versa.',
            'In 1804, a Canadian warship, His Majesty\'s Ship Speedy, sank in Lake Ontario. In 1990, wreck hunter Ed Burtt manage to find it. Only, he isn\'t allowed to recover any artifacts until a government-approved site to exhibit them is found. He\'s still waiting.',
            'Babe Ruth hit his first major league home run at Hanlan\'s Point Stadium in Toronto. It landed in Lake Ontario and is believed to still be there.',
            'A lake on Saturn\'s moon Titan is named after Lake Ontario. It\'s called "Ontario Lacus."'
          ];
module.exports.lakes = lakes;
